package:
  awscli:
    installed: true
  kubeadm:
    installed: true
  kubectl:
    installed: true
  kubelet:
    installed: true
port:
  tcp:10248:
    listening: true
    ip:
    - 127.0.0.1
  tcp6:10250:
    listening: true
    ip:
    - '::'
service:
  containerd:
    enabled: true
    running: true
  kubelet:
    enabled: true
    running: true
process:
  kubelet:
    running: true

