#cloud-config

package_update: true
package_upgrade: true
disable_root: false

packages: [ 'figlet' ]
hostname: "${hostname}"

write_files:
  - path: /etc/bash.bashrc
    permissions: '0755'
    content: !!binary |
      ${master_bashrc}
  - path: /root/.inputrc
    permissions: '0755'
    content: !!binary |
      ${master_inputrc}
  - path: /root/.bash_aliases
    permissions: '0755'
    content: !!binary |
      ${master_aliases}
  - path: /etc/default/motd-news
    owner: root:root
    permissions: '0644'
    content: |
      ENABLED=0
  - path: /etc/pam.d/sshd
    owner: root:root
    permissions: '0644'
    content: |
      # Defaults with comments removed and motd disabled
      @include common-auth
      account    required     pam_nologin.so
      @include common-account
      session [success=ok ignore=ignore module_unknown=ignore default=bad]        pam_selinux.so close
      session    required     pam_loginuid.so
      session    optional     pam_keyinit.so force revoke
      @include common-session
      session    optional     pam_mail.so standard noenv # [1]
      session    required     pam_limits.so
      session    required     pam_env.so # [1]
      session    required     pam_env.so user_readenv=1 envfile=/etc/default/locale
      session [success=ok ignore=ignore module_unknown=ignore default=bad]        pam_selinux.so open
      @include common-password


runcmd:
  - 'systemctl enable docker'
  - 'systemctl daemon-reload'
  - 'systemctl restart docker'
  - 'systemctl restart kubelet'
  - 'mkdir /run/download'
  - 'wget https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml -O /run/download/rbac-kdd.yaml'
  - 'wget https://docs.projectcalico.org/v3.9/manifests/calico.yaml -O /run/download/calico.yaml'
  - 'kubeadm init --pod-network-cidr=192.168.0.0/16'
  - 'mkdir /root/.kube'
  - 'cp /etc/kubernetes/admin.conf /root/.kube/config'
  - 'kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /run/download/rbac-kdd.yaml'
  - 'kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /run/download/calico.yaml'
  - "egrep -A 1 'kubeadm join' /var/log/cloud-init-output.log  |tr -d '\\' | tr -d '\n' > /tmp/join.txt"
  - 'aws s3 cp /tmp/join.txt s3://${s3_bucket_name}'
  - 'aws s3 cp /root/.kube/config s3://${s3_bucket_name}'

output:
  all: '| tee -a /var/log/cloud-init-output.log'
