#cloud-config

# wait for an internet connection
bootcmd:
  - until ping -W 1 -c1 8.8.8.8 >/dev/null; do sleep 1; done

package_update: true
package_upgrade: true
disable_root: false

packages: ["figlet"]
hostname: "${hostname}"

write_files:
  - path: /etc/bash.bashrc
    permissions: "0755"
    content: !!binary |
      ${node_bashrc}
  - path: /root/.inputrc
    permissions: "0755"
    content: !!binary |
      ${node_inputrc}
  - path: /root/.bash_aliases
    permissions: "0755"
    content: !!binary |
      ${node_aliases}
  - path: /etc/default/motd-news
    owner: root:root
    permissions: "0644"
    content: |
      ENABLED=0
  - path: /etc/pam.d/sshd
    owner: root:root
    permissions: "0644"
    content: |
      # Defaults with comments removed and motd disabled
      @include common-auth
      account    required     pam_nologin.so
      @include common-account
      session [success=ok ignore=ignore module_unknown=ignore default=bad]        pam_selinux.so close
      session    required     pam_loginuid.so
      session    optional     pam_keyinit.so force revoke
      @include common-session
      session    optional     pam_mail.so standard noenv # [1]
      session    required     pam_limits.so
      session    required     pam_env.so # [1]
      session    required     pam_env.so user_readenv=1 envfile=/etc/default/locale
      session [success=ok ignore=ignore module_unknown=ignore default=bad]        pam_selinux.so open
      @include common-password

runcmd:
  - 'echo "br_netfilter" >> /etc/modules-load.d/k8s.conf && modprobe br_netfilter'
  - 'echo "net.bridge.bridge-nf-call-iptables = 1" >> /etc/sysctl.d/k8s.conf'
  - 'echo "net.bridge.bridge-nf-call-ip6tables = 1" >> /etc/sysctl.d/k8s.conf'
  - 'echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.d/k8s.conf'
  - 'sysctl --load=/etc/sysctl.d/k8s.conf'
  - "curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -"
  - 'echo "deb https://apt.kubernetes.io/ kubernetes-xenial main"  > /etc/apt/sources.list.d/kubernetes.list'
  - "apt update"
  - "apt install -y containerd kubelet=${version}-00 kubeadm=${version}-00 kubectl=${version}-00 awscli"
  - 'systemctl enable --now containerd'
  - 'systemctl enable --now kubelet'
  - "until aws s3 ls s3://${s3_bucket_name}/join.txt > /dev/null; do sleep 5; done && aws s3 cp s3://${s3_bucket_name}/join.txt /tmp"
  - "until sh /tmp/join.txt; do sleep 5; done"
  - 'curl -L https://github.com/containerd/nerdctl/releases/download/v0.17.0/nerdctl-0.17.0-linux-amd64.tar.gz -o /tmp/nerdctl.tar.gz'
  - 'tar -xf /tmp/nerdctl.tar.gz nerdctl -O > /tmp/nerdctl'
  - 'install /tmp/nerdctl /usr/local/bin/'

output:
  all: "| tee -a /var/log/cloud-init-output.log"
